### PR TITLE
puppet-cron code

### PR DESCRIPTION
**Pull request by danielparks**
Please review! This is very light on comments, but I figured I'd have y'all poke at it an tell me what needs to be cleared up.

See also https://github.com/danielparks/lockfile/commit/ad2135b22802480f58e4946c89f5c89c2a3b8d26

@puppetlabs-operations/infracore

### CODE REVIEW

**Comment by genebean** [comment]
Maybe I am missing something, but how does this know where to find the puppet.conf file?

**Comment by danielparks** [comment]
The puppet agent knows. For example, `puppet config print environment`. It looks in different places depending on what user you run it as (root looks in /etc).

**Comment by danielparks** [comment]
It doesn't interact with puppet.conf directly at all — it's all through `puppet config`.

**Review by richburroughs — COMMENTED** [review]
This looks good to me but I am pretty much a Go noob.

**Comment by danielparks** [comment]
Is there any stuff that particularly needs to be commented? I’ll come back to it in a few days when it’s not so fresh in my head.

**Review by genebean — APPROVED** [review]
I am also a go noob but this looks good and makes sense to me.

**Comment by genebean** [comment]
It might be worthwhile to update the readme to include that this is puppet config print and that it relies on on the system packages as opposed to the ruby gem... that may also be overkill... just some ramblings for your consideration.

**Pull request merged**
